[project]
name = "susurro"
version = "0.1.0"
description = "Transcribe an audio file to text using Whisper."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai-whisper>=20250625",
]
